# Question 1:Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [78]:
# importing numpy
import numpy as np

print(np.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2:Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [79]:
list1 = []
list2 = []

# getting values for list1 from user:
for i in range(5):
  X=int(input("Enter the value for list1 : "))
  list1.append(X)

# getting values for list2 from user:
for i in range(5):
  X=int(input("Enter the value for list2 : "))
  list2.append(X)

# converting list into array:
arr1 = np.array(list1)
arr2 = np.array(list2)
print(type(arr1))
print(type(arr2))

# concatenating 2 array:
arr = np.concatenate((arr1, arr2))
print("concatenated Array :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("Sorted Array :",sortArr)

Enter the value for list1 : 1
Enter the value for list1 : 5
Enter the value for list1 : 7
Enter the value for list1 : 0
Enter the value for list1 : 2
Enter the value for list2 : 20
Enter the value for list2 : 17
Enter the value for list2 : 19
Enter the value for list2 : 4
Enter the value for list2 : 14
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
concatenated Array : [ 1  5  7  0  2 20 17 19  4 14]
Sorted Array : [ 0  1  2  4  5  7 14 17 19 20]


# Question 3:Write a code snippet to find the dimensions of a ndarray and its size.

In [80]:
ar = np.array([1,2,3])
print("No. of dimensions: ", ar.ndim)
print("Size of array: ", ar.size)

No. of dimensions:  1
Size of array:  3


# Question 4:How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

Using np.newaxis

In [82]:
arr = np.arange(5)
print("Shape of Array :",arr.shape)

#rowwise
row_arr = arr[np.newaxis, :]
print("Shape of 2d Array in row major :",row_arr.shape)

#columnwise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)

Shape of Array : (5,)
Shape of 2d Array in row major : (1, 5)

Shape of 2d Array in column major : (5, 1)


Using np.expand_dims

In [83]:
#rowwise
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)

#column wise
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of 2d Array in row major : (1, 5)

Shape of 2d Array in column major : (5, 1)


# Question 5:Consider two square numpy arrays. Stack them vertically and horizontally.Hint: Use vstack(), hstack()

In [84]:
#stacking vertically
arr1 = np.array([1, 7, 3])

arr2 = np.array([10, 5, 4])

arr = np.vstack((arr1, arr2))

print(arr)


[[ 1  7  3]
 [10  5  4]]


In [85]:
#stacking horizontally
arr1 = np.array([1, 7, 3])

arr2 = np.array([10, 5, 4])

arr = np.hstack((arr1, arr2))

print(arr)

[ 1  7  3 10  5  4]


# Question 6:How to get unique items and counts of unique items?

In [86]:
# creating an array 
arr_1 = np.array([1, 4, 9, 16, 25, 1, 4, 2, 3, 2, 5, 6, 5, 7, 8, 10])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

arr = np.asarray((unique, counts)).T

print(arr)

[[ 1  2]
 [ 2  2]
 [ 3  1]
 [ 4  2]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  1]
 [ 9  1]
 [10  1]
 [16  1]
 [25  1]]
